server:
  port: 7001


eureka:
  instance:
    hostname: eureka7001.com
    prefer-ip-address: true
  client:
    register-with-eureka: false  #表示是否将自己注册到Eureka Server，默认是true。
    fetch-registry: false       #表示是否从Eureka Server获取注册信息，默认为true。
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
